# Generated by Django 3.2 on 2024-04-06 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cet4Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(default=0)),
                ('word', models.CharField(max_length=100, unique=True)),
                ('phonetic', models.CharField(blank=True, max_length=255, null=True)),
                ('translation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cet4word',
            },
        ),
        migrations.CreateModel(
            name='UserWord_cet4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.CharField(choices=[('mastered', 'Mastered'), ('familiar', 'Familiar'), ('unknown', 'Unknown')], max_length=10)),
                ('last_reviewed', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybei.cet4word')),
            ],
            options={
                'db_table': 'userword_cet4',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_words', models.IntegerField(default=20)),
                ('study_by_frequency', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usersettings',
            },
        ),
    ]
