# Generated by Django 3.2 on 2024-04-06 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_auto_20240327_1527'),
        ('mybei', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myadmin.user'),
        ),
        migrations.AlterField(
            model_name='userword_cet4',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.user'),
        ),
    ]
