# Generated by Django 3.2 on 2024-04-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybei', '0002_auto_20240406_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='daily_words',
            new_name='daily_new_words',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='daily_review_words',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='userword_cet4',
            name='familiar_count',
            field=models.IntegerField(default=0),
        ),
    ]
