# Generated by Django 3.2 on 2024-04-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybei', '0005_rename_last_study_date_usersettings_last_new_word_fetch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='last_page',
            field=models.IntegerField(default=1),
        ),
    ]
