# Generated by Django 3.2 on 2024-04-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_auto_20240327_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='ai_activated',
            field=models.BooleanField(default=False),
        ),
    ]
